language: python
sudo: false

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

    - python: 3.4
      env: TOXENV=cov
      before_script: pip install -U coveralls
      after_success: coveralls
    - python: 3.4
      env: TOXENV=lint

install: pip install -U tox
script: tox
